import Head from 'next/head';
import Image from 'next/image';
import localFont from 'next/font/local';
import styles from '@/styles/Home.module.css';
import useSWR from 'swr';

import ImagePreview from '@/Components/ImagePreview/ImagePreview';

const fetcher = (...args) => fetch(...args).then((res) => res.json());

export default function Home() {
    const { data, error, isLoading } = useSWR('/api/images', fetcher);
    if (error) return <div>failed to load</div>;
    if (isLoading) return <div>loading...</div>;
    console.log('data', data);
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main>
                <h1>Hello from home</h1>
                {/* <ImagePreview
                    title='Image'
                    url='https://via.placeholder.com/150'
                /> */}
               
                    {data.map((image) => (
                        <ImagePreview
                            key={image._id}
                            title={image.title}
                            url={image.url}
                        />
                    ))}
            </main>
        </>
    );
}
